global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'content-nodes'
    static_configs:
      - targets:
        - 'host.docker.internal:30082'
        - 'host.docker.internal:30083'
        - 'host.docker.internal:30084'
    metrics_path: '/metrics'
    scrape_timeout: 10s
    params:
      'Accept': ['text/plain']