name: Create Deployment PR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to update'
        type: choice
        required: true 
        options:
        - staging
        - prod
        - testnet-sepolia

jobs:
  create-deployment-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Declare variables
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Update deployment
      run: echo "$GITHUB_SHA" > deployments/${{ github.event.inputs.environment }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Deploy ${{ github.event.inputs.environment }} @ ${{ steps.vars.outputs.sha_short }}"
        commit-message: "Deploy ${{ github.event.inputs.environment }} @ ${{ steps.vars.outputs.sha_short }}"
        branch: "release/${{ github.event.inputs.environment }}/${{ steps.vars.outputs.sha_short }}"
        delete-branch: true
