name: Go

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

    - name: Format
      run: |
        DIFF_FILES=$(gofmt -l .)
        if [ -n "$DIFF_FILES" ]; then 
          echo "Some Go source files are incorrectly formatted:"
          echo "$DIFF_FILES"
          exit 1
        fi
