name: Publish Releases

on:
  release:
    types: [ published ]

jobs:
  publish-earthfast-content-node:
    uses: ./.github/workflows/docker-publish.yml
    with:
      dockerfile: Dockerfile.content
      registry: docker.io
      image_name: earthfast/content-node
      labels: |
        org.opencontainers.image.title=EarthFast Content Node
        org.opencontainers.image.url=https://github.com/earthfast
        org.opencontainers.image.source=https://github.com/earthfast
    secrets:
      username: ${{ secrets.DOCKERHUB_USER }}
      password: ${{ secrets.DOCKERHUB_PW }}

  publish-earthfast-domain-node:
    uses: ./.github/workflows/docker-publish.yml
    with:
      dockerfile: Dockerfile.domain
      registry: docker.io
      image_name: earthfast/domain-node
      labels: |
        org.opencontainers.image.title=EarthFast Domain Node
        org.opencontainers.image.url=https://github.com/earthfast
        org.opencontainers.image.source=https://github.com/earthfast
    secrets:
      username: ${{ secrets.DOCKERHUB_USER }}
      password: ${{ secrets.DOCKERHUB_PW }}
